### ISSUE TITLE
Allow paginating queries

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#10]
We can paginate using offset or using a cursor. In both cases a size can be specified.

I suggest adding a new interface/type for cursor-based pagination:

```ts
interface Page {
  private query: Query
  private cursor?: string

  nextPage(size?: number)
  previousPage(size?: number)
  firstPage(size?: number)
  lastPage(size?: number)

  records: readonly XataRecord[]
}
```

And add optional arguments to `getMany()` for offset pagination:

```ts
getMany({
  size?: number,
  offset?: number
})
```

Usage examples:

```ts
// Pagination with offset/size
const users = await xata.db.users.select().getMany()
const users = await xata.db.users.select().getMany({offset: 10})
const users = await xata.db.users.select().getMany({offset: 10, size: 50})
const users = await xata.db.users.select().getMany({size: 50})

// Cursor-based pagination

// Repository implements Page
const page = await xata.db.users.select().nextPage()
const page = await xata.db.users.select().firstPage()
const page = await xata.db.users.select().lastPage()

// Passing a size
const page = await xata.db.users.select().nextPage(100)
const page = await xata.db.users.select().firstPage(100)
const page = await xata.db.users.select().lastPage(100)

// records is an array, not a promise
const users = page.records

// Pages are immutable. Their methods return new pagination objects
const page2 = page.nextPage()
const page2 = page.previousPage()
const page2 = page.firstPage()
const page2 = page.lastPage()

const page2 = page.nextPage(100)
const page2 = page.previousPage(100)
const page2 = page.firstPage(100)
const page2 = page.lastPage(100)
```

**Comment by SferaDev** [comment]
@gimenete I have done an early implementation, will begin writing some tests to see if everything works as expected.

Some questions before opening the PR:

- I don't see the usecase of ``const page = await xata.db.users.select().nextPage()``. In the repository, since we are not still paginating, having ``first`` and ``last`` methods is enough right?

- In my implementation I made the cursor mandatory (whenever you receive a ``Page`` object you get records and a cursor). Did you have in mind any scenario where we didn't have a cursor yet?

- Not sure if we want to hide/show the ``cursor`` in the public API methods (ie. making the fields private and hiding the options from the method options). I believe it is helpful is someone wants to build their own pagination, but could be hard to understand for newcomers. Right now I'm exposing it publicly, as hiding it requires to make separate types for public/internal methods.

- I believe we are not correctly building the objects in ``create`` and ``update`` operations, the API responds only with the id and we're not using the body. I will take a further look when I have this done, but do you recall if it is a known-error? ([Related code](https://github.com/xataio/client-ts/blob/main/client/src/index.ts#L362-L363))
