### ISSUE TITLE
"The workflow is not valid. .github/workflows/build-pr.yml (Line: 34, Col: 9): Unexpected value 'concurrency'"

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#40]
I apologize–seems I naïvely mistakenly [approved this](https://github.com/xataio/client-ts/pull/37#pullrequestreview-911604278) because CI is fully red on `main` right now with the following output.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/9947422/158615463-6ea9a90c-cd0c-408e-8854-f04b12090dcf.png">

**Comment by gimenete** [comment]
This is fixed now. My bad. I thought the concurrency key was at the step level.

I've made the `build` check in PRs required so something like this won't happen again, and also we won't be able to merge PRs with the build failing.

If you don't see the required build running atm it's because there's an incident with GitHub Actions. So delays or totally missing builds are expected.

![image](https://user-images.githubusercontent.com/50486/158622773-447a2f4a-0705-4e5c-a61a-dc50578d35f3.png)

https://www.githubstatus.com/
