### ISSUE TITLE
[Codegen] Should we make the default output path `./generated/XataClient.ts`?

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#47]
Generally I think it makes sense to make it very clear that the XataClient is _generated_ and not intended to be manually changed, so I'm wondering if it's a good idea to make this even more explicit with a directory by default. Of course, users can choose other output paths and it'll follow nicely.

We could even add a banner on top of the file stating something like this.

Would that be good developer experience?

**Comment by gimenete** [comment]
> We could even add a banner on top of the file stating something like this.

I prefer that.

I don't like the option of creating a `generated` folder by default, because we just generate a single file. The banner option feels simpler and nicer to me.

**Comment by TejasQ** [comment]
![why not both?](https://media.giphy.com/media/Pd2W87rlmVjptTmvIK/giphy.gif)

This is learning from the Xata CLI, who started with `schema.json` and then decided they need a folder. We could even output directly in this folder to separate Xata concerns from our user's source code. 🤯

**Comment by gimenete** [comment]
> Why not both

Like I said: _I don't like the option of creating a generated folder by default, because we just generate a single file_

Besides, people may think that a `generated` directory is not something they should track in git or something like that, and may cause friction.

> We could even output directly in this folder to separate Xata concerns from our user's source code.

I don't dislike this opiton, but it could generate problems with the `xata` cli, if it decides to remove the directory or something to reset the state at some point, etc.

In general I prefer to have all my code in a `src` directory, and I think that's what most people do. Then configuration files in other directories (e.g. `xata`). This makes things easier to configure. For example the tsconfig file.
