### ISSUE TITLE
Cannot create a Xata branch without a remote

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#471]
**Describe the bug**
`xata branches create dev`, in a git repo at a specific branch (`main` in this case) fails to infer the base branch and complains about "No git remotes found". Given that HEAD is already `main` here, a remote should not be required.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/9947422/180146651-0e602b2c-dce0-4313-88a9-98e32b1a3c94.png">

**To Reproduce**

Run `xata branches create dev` in a repo with no remotes.

**Expected behavior**

A branch with the specified name is created in git and in Xata.

**Software version**

`@xata.io/cli/0.6.0 darwin-arm64 node-v16.15.1`

**Comment by gimenete** [comment]
A remote is needed in git to calculate the default branch. Here's [an article that explains how to get the value](https://joshtronic.com/2020/08/09/how-to-get-the-default-git-branch/).

Note: when opening bugs, could you remove the template instructions? It's hard to know what's your text and what's the template text.

**Comment by TejasQ** [comment]
> A remote is needed in git to calculate the default branch. Here's [an article that explains how to get the value](https://joshtronic.com/2020/08/09/how-to-get-the-default-git-branch/).

Why do we base a new branch on the default branch instead of the current branch? `git checkout -b new` is automatically based on whatever is currently checked out instead of the default branch. I'd expect Xata branches to work the same.

**Comment by gimenete** [comment]
> Why do we base a new branch on the default branch instead of the current branch? git checkout -b new is automatically based on whatever is currently checked out instead of the default branch. I'd expect Xata branches to work the same.

Git is more flexible because there are many types of software you can do with it. For example you can work on different versions of the same software and release them at the same time (1.x, 2.x,..., being some of them in maintenance).

However in our use case you typically will only have one production branch and db branches are much less often used than git branches. So, the use case of branching off an existing branch that is not main, in my opinion will be a lot less common than the case of branching off main.

But we can discuss this with Tudor.

**Comment by TejasQ** [comment]
Great idea not pinging him because vacation.gif 🙌

**Comment by SferaDev** [comment]
I think that we don't need to provide all the flexibility of git, however needing `A <- B <- C` doesn't seem that unlikely specially if you use git.

**Comment by gimenete** [comment]
>  I think we should allow changing base branch when creating a new one.

We allow that with the `--from` flag. I think the discussion is more about which one is the default.

**Comment by TejasQ** [comment]
Yeah, my only suggestion is to follow git 1:1 since that's what developers are more familiar with. :)

**Comment by tsg** [comment]
Sorry for the delay here, if I understand correctly, the options are:

1. we default to fork from `main` if no `--form` is specified
2. we use the resolve endpoint to figure out if there is a Xata branch linked to the current git branch, and if there is, we use it as the default to fork from. If it isn't, we still use `main` as the default.

Would option 2 be difficult from an implementation PoV? If not, I think I like it, because if you have just created the git feature branch and do `xata branches create`, it still defaults to `main`. But if you are in a feature branch and that is already created , then it's more likely that you want to branch from it.

Btw, are we automatically linking the git branch with the xata branch if you do `xata branches create` while in a git branch?

**Comment by SferaDev** [comment]
Will be revamped as part of #p-worflow
