### ISSUE TITLE
`.query` types are not so obvious and I'm a bit blocked

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#5]
Not sure what is expected here:

![image](https://user-images.githubusercontent.com/9947422/152832429-46adf4ff-8047-41cc-9ebf-1c7f36e729e2.png)

I tried an object, but

![image](https://user-images.githubusercontent.com/9947422/152832585-f357e224-9e00-478e-bc4c-75972871594a.png)

Why does it need `table` if I'm already querying `db.users`?

I searched the README but couldn't find anywhere this is covered too 😢

**Comment by gimenete** [comment]
> I searched the README but couldn't find anywhere this is covered too 😢

Because it's meant to be used internally. It's used for another internal class so I could not really make it `private`. We'll need to figure something.

There's no harm on using it, in fact people can use it. And the argument is a `Query`, which you can get with the `select()` method that is explained in the README.

**Comment by fabien0102** [comment]
We can also be modern and use `#query` -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

**Comment by gimenete** [comment]
@fabien0102 like I said, I couldn't make it private because it's used for other class.

> Maybe we use _query

Yeah, that can be a good idea.

**Comment by SferaDev** [comment]
Closing stale issue
