### ISSUE TITLE
Discussion: separate code generation from xata init

### ISSUE THREAD

**Issue by tsg** [xataio/client-ts#520]
In a discussion following from #504 an alternative idea came up: We could remove the installation of the code generator from the `xata init` to the first run of `xata codegen`.

The advantages that I see:
* `xata init` is kept language-agnostic which avoids avoiding the feeling that we are for JS/TS only
* we avoid 2 questions during `xata init` and potential failures from the extra things that we run (including an `npm` command?)
* people might do init before they define the schema (e.g. we allow "Create new DB" as an option, in which case it will be empty), so in that case they'll need to run `xata codegen` again after doing the schema anyway

The disadvantage is that types are not ready to use when `xata init` is done, you need a second command (`xata codegen`).

@TejasQ did a quick survey of other tools, and it seems it's common to require a second step after `init` (e.g. `prisma init` + `prisma generate`).

Are there any pros/cons that I missed? Any strong opinions one way or the other?

**Comment by tsg** [comment]
Or perhaps there's a point to having `xata init --javascript` and `xata init --typescript`?

**Comment by gimenete** [comment]
We already have `xata init --codegen src/xata.ts` which will not ask the user. My concern is that people won't know about it and for most of our users (which will be ts/js users) they will get stuck because they don't have their projects fullly configured. Besides, I don't think it's a big deal to ask simple questions that are easy to understand in `xata init` for this.

To me `xata init` should configure the project as the user needs, and other commands should not affect the configuration. As far as I understand, that's the case with `prisma init` as well:

![image](https://user-images.githubusercontent.com/50486/183040581-72df2f88-f560-4c32-9155-17be622149a9.png)

We have the same: prisma init + prisma generate is equivalent to xata init + xata codegen. The generate/codegen does not configure the project, but just generates things according to your existing configuration, that you defined in `xata init`.

**Comment by gimenete** [comment]
What about this? https://github.com/xataio/client-ts/pull/549

With that PR it will only be one question and there's no code snippet anymore.

![](https://user-images.githubusercontent.com/50486/184317480-de3e5b81-65a5-4e00-8bdd-cca70d97e5d8.png)

**Comment by SferaDev** [comment]
I love it, and in the future we could even add other languages!

**Comment by gimenete** [comment]
Thanks Alexis!

Btw, I'm thinking that maybe we can put the snippet back, but after you made the choice so it's not noisy if you don't choose code generation, and we can even generate a more personalized snippet based on your choice.

**Comment by tsg** [comment]
Thanks for the new proposal, I think it's nice. To build up on it, how about:

We first ask:

```
? What programming language do you plan to use?
   > TypeScript
     JavaScript
     Other/None
```

Then for TypeScript we ask:

```
Do you want to use code generation for your types?
   > Yes (recommended)
     No
```

And for Javascript:

```
 Do you want to use code generation in your project?
   > Generate code with ES modules
     Generate code with CJS (require)
     Install the Javascript SDK only, no code generation
```

And for "Others/none" we do nothing.

I know this is adding an extra question and I was on a quest to reduce how many questions we ask, but the question on "what programming language you use" is so simple and effortless to answer that I think it almost doesn't count. It also gives us a clear positioning that we are planning to support multiple programming languages (and I hope to have at least a simple Python SDK soonish).

**Comment by richardgill** [comment]
I think this is done.
