### ISSUE TITLE
`getById` method

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#558]
**Is your feature request related to a problem? Please describe.**
During my implementation of `/resources/:id` route, I was looking how to get a record by id.

Since a lot of the SDK method are starting by `get`, I was looking in this direction. At the end the `.read(id)` method is doing the job.

**Describe the solution you'd like**
I would love a `getById` or `getRecord` method. This feels more natural than `read` aside of the `getPaginated` calls.

**Describe alternatives you've considered**
I'm currently using `.read` and this is working perfectly 😃

**Comment by SferaDev** [comment]
The `getX` operations are `execute` methods for a given query. So get `getRecord` or `getById` wouldn't be consistent with the rest of `getX` operations.

`read` instead is consistent with the `create`, `update`, `createOrUpdate` or `delete` which are CRUD naming for the operations at the repository level (not query). Also the parameters between them are consistent (which your proposed one wouldn't be with `getX` ones.

There was an initial discussion of naming choices and consistency, and this is what we agreed on. We can have a chat about it tomorrow, but I don't think we should change the naming or add aliases in this particular case.

Alternatively, we could have `findX` methods for `findById`, `findByName` and with reflexion offer it for all columns. But I'd like to wait until we have more statistics on what our users are building and which methods are they using, for example if instead of using `read` they build more `getFirst({ filter: { id } })`. Sounds good?

**Comment by fabien0102** [comment]
Good to me, this was just to give a bit of my feedback. I now understand what is the design! Thanks for the context 💯
