### ISSUE TITLE
Investigate npx no install

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#89]
```
npm i @xata.io/codegen -D
npm i @xata.io/client
xata pull
npx xata-codegen -c xata/config.json
```

vs

```
npx https://app.xata.io/sdk/my-project/db/branch
```

**Comment by fabien0102** [comment]
I play around this idea, we can easily provide a `npx https://app.xata.io/sdk/my-project/db/branch` by serving a `tar.gz` with a `package.json` inside. This can also works with `npm i https://app.xata.io/sdk/my-project/db/branch` (even cooler).

But the major problem is the auth, since the xata schema is not public. With this in mind, we could generate a unique token for this, but the DX is not as good (and this add a lot of complexity)

Anyway, playing a bit and thinking about it, I think a classic npm package is still better.

```
$ npx @xata.io/client
> What's your token?
> Select your workspace
> Select your database
> Select your branch
> Where do you want to generate the SDK?
> 🦋 You are ready to go! 🦋
```
This could generate the SDK and `package.json`, end of story!
