### ISSUE TITLE
CSV Import - create link columns

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#924]
Currently (`cli/0.11.9`) the csv importer errors when a link column type is specified, for example:

```
xata import csv my.csv --table mytable --create --columns=mylink --types=link
```

Error output:
```
Error: invalid migration: addColumn: field [column]: missing link configuration
```

Please add support for creating link columns.

**Comment by eemmiillyy** [comment]
This have been fixed in subsequent releases. One thing to note is that in order to import a table that has a link column, the user needs to first create the table that it links to. The name of the link column also needs to match the name of the table that it links to. This carries the limitation of only one link per table x to table y.
